version: '3.9'
name: BotJDE

networks:
  db:
    driver: bridge
volumes:
  db:

services:
  botjde:
    build:
      context: .
    container_name: botjde
    restart: unless-stopped
    networks:
      - db
    ports:
      - "8080:8080"
    environment:
      - A=B
    volumes:
      - ./../:/app
    working_dir: /app
    command: gradle bootrun
    depends_on:
      database:
        condition: service_healthy
  database:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: botjde
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - db
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d botjde -U ${POSTGRES_USER}" ]
      interval: 30s
      timeout: 10s
      retries: 5