version: '3.9'
name: BotJDE

networks:
  db:
    driver: bridge
volumes:
  logs:
  db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/Dev/dbs/botjde

services:
  botjde:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: botjde:latest
    container_name: botjde
    restart: unless-stopped
    networks:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Duser.timezone=America/New_York
      - TZ=America/New_York
    volumes:
      - ../logs:/app/logs 
    depends_on:
      database:
        condition: service_healthy
  database:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: botjde
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - db
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d botjde -U ${POSTGRES_USER}" ]
      interval: 30s
      timeout: 10s
      retries: 5