version: '3.9'

networks:
  db:
    driver: bridge
volumes:
  db:

services:
  botjde:
    build:
      context: .
      dockerfile: application.Dockerfile
    container_name: botjde
    # restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - A=B
    volumes:
      - ./../:/app
    working_dir: /app
    command: gradle bootrun
    depends_on:
      database:
        condition: service_healthy
  database:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: botjde
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - db:/home/snip3sh0t/Dev/dbs/botjde
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U ${POSTGRES_USER}" ]
      interval: 30s
      timeout: 10s
      retries: 5